[dependencies]
base = "0.10.2"
time-consts = "1.0.0"
map = "8.1.0"
ic = "0.2.0"
backup = "1.1.0"
sha2 = "0.0.4"
vector = "0.2.0"
http-types = "1.0.0"
datetime = "0.1.3"

[dev-dependencies]
test = "1.0.0"
fuzz = "0.1.1"
bench = "1.0.0"