[dependencies]
base = "0.10.3"
time-consts = "1.0.1"
map = "9.0.1"
ic = "1.0.1"
backup = "1.1.1"
sha2 = "0.0.4"
vector = "0.2.0"
http-types = "1.0.0"
datetime = "0.1.3"

[dev-dependencies]
test = "1.2.0"
fuzz = "0.2.0"
bench = "1.0.0"

[toolchain]
moc = "0.10.3"
wasmtime = "16.0.0"
pocket-ic = "1.0.0"