[dependencies]
base = "0.9.4"
time-consts = "1.0.0"
map = "8.1.0"
ic = "0.2.0"
backup = "1.1.0"
datetime = "0.1.0"
chronosphere = "https://github.com/enzoh/chronosphere#master"

[dev-dependencies]
test = "1.0.0"
fuzz = "0.1.0"