[package]
name = "lib"
version = "1.2.0"
description = "Test lib"
repository = ""

[dependencies]
base = "0.6.27"
http-parser = "0.1.0"
"Itertools.mo" = "https://github.com/NatLabs/Itertools.mo#master"
serde = "https://github.com/NatLabs/serde#master"