[dependencies]
base = "0.11.2"
time-consts = "1.0.1"
map = "9.0.1"
ic = "1.0.1"
backup = "3.0.0"
sha2 = "0.0.6"
vector = "0.4.0"
http-types = "1.0.1"
datetime = "0.3.0"

[dev-dependencies]
test = "2.0.0"
fuzz = "0.2.1"
bench = "1.0.0"

[toolchain]
moc = "0.11.2"
wasmtime = "22.0.0"
pocket-ic = "1.0.0"