name: Build CLI and print hash

on:
  push:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-24.04, ubuntu-22.04-arm, ubuntu-24.04-arm]
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker
        uses: docker/setup-docker-action@v4
      - name: Build using Docker
        run: |
          # MOPS_VERSION=$(cd cli && npm pkg get version | tr -d \")
          # echo MOPS_VERSION=$MOPS_VERSION
          # if [ -z "$MOPS_VERSION" ]; then
          #   echo "MOPS_VERSION is empty"
          #   exit 1
          # fi
          MOPS_VERSION=0.0.0
          cd cli
          docker build . --build-arg COMMIT_HASH=${{ github.sha }} --build-arg MOPS_VERSION=$MOPS_VERSION -t mops
          OUTPUT=$(docker run --rm mops || echo ".")
          echo "$OUTPUT" >> $GITHUB_STEP_SUMMARY