name: Build CLI and print hash

on:
  push:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: |
          MOPS_VERSION=$(cd cli && npm pkg get version | tr -d \")
          echo MOPS_VERSION=$MOPS_VERSION
          if [ -z "$MOPS_VERSION" ]; then
            echo "MOPS_VERSION is empty"
            exit 1
          fi
          cd verify
          docker build . --build-arg COMMIT_HASH=${{ github.sha }} --build-arg MOPS_VERSION=$MOPS_VERSION -t mops
          docker run --rm mops || echo "."