name: CI

on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: aviate-labs/setup-dfx@v0.2.3
        with:
          dfx-version: 0.14.0

      - name: Select moc version
        run: echo "DFX_MOC_PATH=$(npx mocv bin 0.9.1)/moc" >> $GITHUB_ENV

      - name: Build and Deploy Frontend
        run: |
            npm i
            npm i -g ./cli
            mops install
            npm run replica
            npm run deploy
            npm run build

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Lint
        run: |
            npm i
            npm run lint

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: aviate-labs/setup-dfx@v0.2.3
        with:
          dfx-version: 0.14.0

      - name: Select moc version
        run: echo "DFX_MOC_PATH=$(npx mocv bin 0.9.1)/moc" >> $GITHUB_ENV

      - name: Install npm packages
        run: |
            cd cli
            npm install

      - name: Run Tests
        run: |
            npm i -g ./cli
            mops install
            dfx cache install
            mops test

