name: CI

on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        moc-version: [0.9.3, 0.9.7]
        mops-version: [./cli, ic-mops@latest, ic-mops@0.12, ic-mops@0.14]
        node-version: [16, 18, 20]

    runs-on: ubuntu-latest
    name: node ${{ matrix.node-version }}, moc ${{ matrix.moc-version }}, ${{ matrix.mops-version }}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - uses: aviate-labs/setup-dfx@v0.2.6
        with:
          dfx-version: 0.14.1

      - name: Cache mops packages
        uses: actions/cache@v3
        with:
          key: mops-packages-${{ hashFiles('mops.toml') }}
          path: |
            ~/.cache/mops
            ~/mops

      - name: Select moc version
        run: npx mocv use ${{ matrix.moc-version }}

      - name: Install mops
        run: npm i -g ${{ matrix.mops-version }}

      - name: Install npm packages
        run: npm install

      - name: Install mops packages
        run: mops install

      - name: Build and Deploy
        run: |
            npm run replica
            npm run deploy-local
            npm run build