name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: aviate-labs/setup-dfx@v0.2.3
        with:
          vessel-version: 0.6.3
          dfx-version: 0.13.0

      - name: Build and Deploy Frontend
        run: |
            npm i
            node cli/cli.js install
            npm run replica
            npm run deploy
            npm run build

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Lint
        run: |
            npm i
            npm run lint

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: aviate-labs/setup-dfx@v0.2.3
        with:
          vessel-version: 0.6.3
          dfx-version: 0.13.0

      - name: Run Tests
        run: |
            npm i
            npm i -g .
            mops install
            dfx cache install
            mops test

