name: CLI bundle

on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        node-version: [22]
        os: [ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }}, node ${{ matrix.node-version }}

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install npm dependencies
        run: cd cli && npm i --ignore-scripts

      - name: Prepare
        run: cd cli && npm run prepare

      - name: Bundle
        run: cd cli && npm run bundle

      - name: Check local bundle
        run: node ./cli/bundle/cli.js -v

      - name: Install bundle globally
        run: npm i -g ./cli/bundle/cli.tgz

      - name: Check global bundle
        run: mops -v