name: mops test with ZenVoich/setup-mops

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test with ZenVoich/setup-mops

    steps:
      - uses: actions/checkout@v4
      - uses: dfinity/setup-dfx@main
      - uses: ZenVoich/setup-mops@v1
        with:
          mops-version: 1.0.0
      - name: Run tests
        run: mops test